### ISSUE TITLE
How to find the dataset features and annotations used in GTEA, BEOID, and ActivityNet 1.3?

### ISSUE THREAD

**Issue by daidaiershidi** [pipixin321/HR-Pro#1]
Thank you for the significant advancements you've brought. I am a beginner in this fields. Could you please guide me on how to find the dataset features and annotations used in GTEA, BEOID, and ActivityNet 1.3?

**Comment by pipixin321** [comment]
Thanks for your interest! 
For the video features and annotations of  GTEA and BEOID, You can find them [here](https://github.com/Flowerfan/SF-Net).
For the video features of ActivityNet1.3, we used the features provided in [here](https://github.com/ispc-lab/ACM-Net),
As far as we know, there are no publicly available point annotations for the ActivityNet 1.3 dataset，we generated point annotations based on Gaussian distribution from fully annotated data, we plan to release them in the future.

**Comment by daidaiershidi** [comment]
Thank you very much for your response. The link in the first repository is not working. May I inquire if there are alternative repositories that provide the corresponding features?

**Comment by pipixin321** [comment]
I can open it myself, maybe you can try to download the thumos14 video features provided in [here](https://github.com/Pilhyeon/Learning-Action-Completeness-from-Points?tab=readme-ov-file), which is the same. If it still doesn't work, you can check your network connection.

**Comment by daidaiershidi** [comment]
I sincerely apologize for any misunderstanding caused by my previous communication. What I intended to convey is that I have noticed the Google Drive link provided by SF-Net is no longer valid. Additionally, I have reached out to the author of SF-Net via email for clarification, but unfortunately, I have not received a response thus far.

**Comment by pipixin321** [comment]
In the latest commit, we have added video features for the BEOID and GTEA datasets, along with all the point annotations files we used. Please check it!

**Comment by ShengJinrongcqu** [comment]
How do I get proposals from stage 1 and then use them in stage 2?
Do you approve of this approach?

**Comment by pipixin321** [comment]
> How do I get proposals from stage 1 and then use them in stage 2? Do you approve of this approach?
As mentioned in the README, you can run `python main.py --cfg thumos --stage 1 --mode test` to get proposals，
and there should be `proposals.json`  in the output path of stage 1.
After that, you can run `python main.py --cfg thumos --stage 2 --mode train`, and the dataset class will automatically import proposals.
You can refer to `ranking.py` and `dataset.py` for more detail.

**Comment by ShengJinrongcqu** [comment]
thanks

**Comment by ssp-seven** [comment]
> > 如何从阶段 1 获取提案，然后在阶段 2 中使用它们？您赞成这种方法吗？正如 README 中提到的，你可以运行 来获取提案，并且第 1 阶段的输出路径中应该有。之后，您可以运行 ，dataset 类将自动导入提案。您可以参考 和 了解更多详细信息。`python main.py --cfg thumos --stage 1 --mode test``proposals.json``python main.py --cfg thumos --stage 2 --mode train``ranking.py``dataset.py`
大佬好，请问方便公开另外三个数据集的cfgs文件嘛？十分感谢！
