### ISSUE TITLE
About ActivityNet1.3 Point_labels

### ISSUE THREAD

**Issue by CL2LC** [pipixin321/HR-Pro#2]
Thank for you great work! 
However, I'm wondering about the ActivityNet1.3 point_labels file: 
Why is its' start_frame 'and' stop_frame 'not integer but float type, and does 'point' provide the frame index ?

**Comment by pipixin321** [comment]
Thank you for your interest!
The start frame and end frame are calculated by `time(s)*fps`, so they are not necessarily integer values, and the point label is the frame index as you understand it.
